/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "xnor2" *)
(* top =  1  *)
(* src = "xnor2.soln.sv:1.1-5.10" *)
module xnor2(b_i, c_o, a_i);
  (* src = "xnor2.soln.sv:1.20-1.23" *)
  input b_i;
  wire b_i;
  (* src = "xnor2.soln.sv:1.32-1.35" *)
  output c_o;
  wire c_o;
  (* src = "xnor2.soln.sv:1.43-1.46" *)
  input a_i;
  wire a_i;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  assign _00_ = b_i & a_i;
  assign _01_ = _03_ & _04_;
  assign _02_ = _05_ & _06_;
  assign _03_ = ~b_i;
  assign _04_ = ~a_i;
  assign _05_ = ~_00_;
  assign _06_ = ~_01_;
  assign c_o = _02_;
endmodule
