/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "gray2bin" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "gray2bin.soln.sv:1.1-23.10" *)
module gray2bin(gray_i, bin_o);
  (* src = "gray2bin.soln.sv:3.29-3.35" *)
  input [4:0] gray_i;
  wire [4:0] gray_i;
  (* src = "gray2bin.soln.sv:4.31-4.36" *)
  output [4:0] bin_o;
  wire [4:0] bin_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  assign _00_ = _19_ & _20_;
  assign _01_ = bin_o[3] & gray_i[2];
  assign _02_ = _09_ & _10_;
  assign _03_ = _11_ & _12_;
  assign _04_ = bin_o[2] & gray_i[1];
  assign _05_ = _13_ & _14_;
  assign _06_ = _15_ & _16_;
  assign _07_ = gray_i[4] & gray_i[3];
  assign _08_ = _17_ & _18_;
  assign _09_ = ~bin_o[3];
  assign _10_ = ~gray_i[2];
  assign _11_ = ~_01_;
  assign _12_ = ~_02_;
  assign _13_ = ~bin_o[2];
  assign _14_ = ~gray_i[1];
  assign _15_ = ~_04_;
  assign _16_ = ~_05_;
  assign _17_ = ~gray_i[4];
  assign _18_ = ~gray_i[3];
  assign _19_ = ~_07_;
  assign _20_ = ~_08_;
  assign { bin_o[4], bin_o[0] } = { gray_i[4], 1'hx };
  assign bin_o[3] = _00_;
  assign bin_o[2] = _03_;
  assign bin_o[1] = _06_;
endmodule
