/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "one_hot_mux" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "one_hot_mux.soln.sv:1.1-36.10" *)
module one_hot_mux(data_i, sel_one_hot_i, data_o);
  (* src = "one_hot_mux.soln.sv:5.36-5.42" *)
  input [63:0] data_i;
  wire [63:0] data_i;
  (* src = "one_hot_mux.soln.sv:6.24-6.37" *)
  input [7:0] sel_one_hot_i;
  wire [7:0] sel_one_hot_i;
  (* src = "one_hot_mux.soln.sv:7.27-7.33" *)
  output [7:0] data_o;
  wire [7:0] data_o;
  (* src = "one_hot_mux.soln.sv:10.36-10.47" *)
  wire [63:0] data_masked;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[0].gather ;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[1].gather ;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[2].gather ;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[3].gather ;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[4].gather ;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[5].gather ;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[6].gather ;
  (* src = "one_hot_mux.soln.sv:21.26-21.32" *)
  wire [7:0] \reduce[7].gather ;
  assign data_masked = 64'hxxxxxxxxxxxxxxxx;
  assign data_o = 8'hff;
  assign \reduce[0].gather  = 8'hxx;
  assign \reduce[1].gather  = 8'hxx;
  assign \reduce[2].gather  = 8'hxx;
  assign \reduce[3].gather  = 8'hxx;
  assign \reduce[4].gather  = 8'hxx;
  assign \reduce[5].gather  = 8'hxx;
  assign \reduce[6].gather  = 8'hxx;
  assign \reduce[7].gather  = 8'hxx;
endmodule
