/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "full_add" *)
(* top =  1  *)
(* src = "full_add.soln.sv:1.1-12.10" *)
module full_add(a_i, b_i, carry_i, carry_o, sum_o);
  (* src = "full_add.soln.sv:2.16-2.19" *)
  input [0:0] a_i;
  wire [0:0] a_i;
  (* src = "full_add.soln.sv:3.16-3.19" *)
  input [0:0] b_i;
  wire [0:0] b_i;
  (* src = "full_add.soln.sv:4.16-4.23" *)
  input [0:0] carry_i;
  wire [0:0] carry_i;
  (* src = "full_add.soln.sv:5.17-5.24" *)
  output [0:0] carry_o;
  wire [0:0] carry_o;
  (* src = "full_add.soln.sv:6.17-6.22" *)
  output [0:0] sum_o;
  wire [0:0] sum_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  assign _07_ = _16_ & _17_;
  assign _01_ = _18_ & _08_;
  assign _02_ = _00_ & carry_i;
  assign _03_ = _10_ & _11_;
  assign _04_ = _12_ & _13_;
  assign _05_ = carry_i & _15_;
  assign _06_ = b_i & 1'bx;
  assign _08_ = ~_07_;
  assign _09_ = ~_01_;
  assign _10_ = ~_00_;
  assign _11_ = ~carry_i;
  assign _12_ = ~_02_;
  assign _13_ = ~_03_;
  assign _14_ = ~_04_;
  assign _15_ = ~_00_;
  assign _16_ = ~b_i;
  assign _17_ = 1'bx;
  assign _18_ = ~_06_;
  assign _00_ = _09_;
  assign sum_o = _14_;
  assign carry_o = _05_;
endmodule
