/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "bin2gray" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "bin2gray.soln.sv:1.1-8.10" *)
module bin2gray(bin_i, gray_o);
  (* src = "bin2gray.soln.sv:3.28-3.33" *)
  input [4:0] bin_i;
  wire [4:0] bin_i;
  (* src = "bin2gray.soln.sv:4.29-4.35" *)
  output [4:0] gray_o;
  wire [4:0] gray_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  assign _00_ = _20_ & _09_;
  assign _01_ = bin_i[1] & bin_i[3];
  assign _02_ = _10_ & _11_;
  assign _03_ = _12_ & _13_;
  assign _04_ = bin_i[4] & bin_i[2];
  assign _05_ = _14_ & _15_;
  assign _06_ = _16_ & _17_;
  assign _07_ = bin_i[0] & bin_i[2];
  assign _08_ = _18_ & _19_;
  assign _09_ = ~_08_;
  assign _10_ = ~bin_i[1];
  assign _11_ = ~bin_i[3];
  assign _12_ = ~_01_;
  assign _13_ = ~_02_;
  assign _14_ = ~bin_i[4];
  assign _15_ = ~bin_i[2];
  assign _16_ = ~_04_;
  assign _17_ = ~_05_;
  assign _18_ = ~bin_i[0];
  assign _19_ = ~bin_i[2];
  assign _20_ = ~_07_;
  assign gray_o[4:3] = bin_i[4:3];
  assign gray_o[0] = _00_;
  assign gray_o[1] = _03_;
  assign gray_o[2] = _06_;
endmodule
