/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "mux2" *)
(* top =  1  *)
(* src = "mux2.soln.sv:1.1-15.10" *)
module mux2(a_i, b_i, select_i, c_o);
  (* src = "mux2.soln.sv:2.16-2.19" *)
  input [0:0] a_i;
  wire [0:0] a_i;
  (* src = "mux2.soln.sv:3.16-3.19" *)
  input [0:0] b_i;
  wire [0:0] b_i;
  (* src = "mux2.soln.sv:4.16-4.24" *)
  input [0:0] select_i;
  wire [0:0] select_i;
  (* src = "mux2.soln.sv:5.17-5.20" *)
  output [0:0] c_o;
  wire [0:0] c_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  assign _01_ = a_i & select_i;
  assign _02_ = _07_ & _08_;
  assign _03_ = _09_ & _10_;
  assign _04_ = _00_ & b_i;
  assign _05_ = _11_ & _12_;
  assign _06_ = _13_ & _14_;
  assign _07_ = ~a_i;
  assign _08_ = ~select_i;
  assign _09_ = ~_01_;
  assign _10_ = ~_02_;
  assign _11_ = ~_00_;
  assign _12_ = ~b_i;
  assign _13_ = ~_04_;
  assign _14_ = ~_05_;
  assign _00_ = _03_;
  assign c_o = _06_;
endmodule
