/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "one_hot_enc" *)
(* src = "one_hot_enc.soln.sv:2.1-80.10" *)
module one_hot_enc(i, addr_o, v_o);
  (* src = "one_hot_enc.soln.sv:3.22-3.23" *)
  input [7:0] i;
  wire [7:0] i;
  (* src = "one_hot_enc.soln.sv:4.32-4.38" *)
  output [2:0] addr_o;
  wire [2:0] addr_o;
  (* src = "one_hot_enc.soln.sv:5.10-5.13" *)
  output v_o;
  wire v_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  (* unused_bits = "16 17 20 21" *)
  wire [26:0] addr;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[0].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[1].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[2].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[3].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \rof[2].rof1[0].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \rof[2].rof1[1].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[3].rof1[0].vs ;
  (* unused_bits = "10 14" *)
  wire [24:0] v;
  assign _07_ = _18_ & _19_;
  assign _08_ = _21_ & _22_;
  assign _09_ = _24_ & _25_;
  assign _10_ = _27_ & _28_;
  assign _11_ = _30_ & _31_;
  assign _12_ = _33_ & _34_;
  assign _13_ = _36_ & _37_;
  assign _14_ = _39_ & _40_;
  assign _15_ = _42_ & _43_;
  assign _16_ = _45_ & _46_;
  assign _17_ = _48_ & _49_;
  assign _18_ = ~i[5];
  assign _19_ = ~i[4];
  assign _20_ = ~_07_;
  assign _21_ = ~i[7];
  assign _22_ = ~i[6];
  assign _23_ = ~_08_;
  assign _24_ = ~_01_;
  assign _25_ = ~_00_;
  assign _26_ = ~_09_;
  assign _27_ = ~i[1];
  assign _28_ = ~i[0];
  assign _29_ = ~_10_;
  assign _30_ = ~i[3];
  assign _31_ = ~i[2];
  assign _32_ = ~_11_;
  assign _33_ = ~_03_;
  assign _34_ = ~_02_;
  assign _35_ = ~_12_;
  assign _36_ = ~_04_;
  assign _37_ = ~addr_o[2];
  assign _38_ = ~_13_;
  assign _39_ = ~i[3];
  assign _40_ = ~i[1];
  assign _41_ = ~_14_;
  assign _42_ = ~i[7];
  assign _43_ = ~i[5];
  assign _44_ = ~_15_;
  assign _45_ = ~_06_;
  assign _46_ = ~_05_;
  assign _47_ = ~_16_;
  assign _48_ = ~_03_;
  assign _49_ = ~_01_;
  assign _50_ = ~_17_;
  assign { addr[26:22], addr[19:18], addr[15:0] } = { addr_o, 5'hxx, i[7], 1'hx, i[5], 1'hx, i[3], 1'hx, i[1], 8'h00 };
  assign \rof[1].rof1[0].vs  = i[1:0];
  assign \rof[1].rof1[1].vs  = i[3:2];
  assign \rof[1].rof1[2].vs  = i[5:4];
  assign \rof[1].rof1[3].vs  = i[7:6];
  assign \rof[2].rof1[0].vs  = { addr[17], 1'hx };
  assign \rof[2].rof1[1].vs  = { addr[21], 1'hx };
  assign \rof[3].rof1[0].vs  = { addr_o[2], 1'hx };
  assign v = { v_o, 3'hx, addr_o[2], 5'hxx, addr[21], 3'hx, addr[17], 2'hx, i };
  assign _00_ = _20_;
  assign _01_ = _23_;
  assign addr_o[2] = _26_;
  assign _02_ = _29_;
  assign _03_ = _32_;
  assign _04_ = _35_;
  assign v_o = _38_;
  assign _05_ = _41_;
  assign _06_ = _44_;
  assign addr_o[0] = _47_;
  assign addr_o[1] = _50_;
endmodule
