/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "one_hot_enc" *)
(* src = "one_hot_enc.soln.sv:2.1-80.10" *)
module one_hot_enc(i, addr_o, v_o);
  (* src = "one_hot_enc.soln.sv:3.22-3.23" *)
  input [7:0] i;
  wire [7:0] i;
  (* src = "one_hot_enc.soln.sv:4.32-4.38" *)
  output [2:0] addr_o;
  wire [2:0] addr_o;
  (* src = "one_hot_enc.soln.sv:5.10-5.13" *)
  output v_o;
  wire v_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  (* unused_bits = "16 17 20 21" *)
  wire [26:0] addr;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[0].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[1].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[2].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[1].rof1[3].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \rof[2].rof1[0].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \rof[2].rof1[1].vs ;
  (* src = "one_hot_enc.soln.sv:30.22-30.24" *)
  wire [1:0] \rof[3].rof1[0].vs ;
  (* unused_bits = "10 14" *)
  wire [24:0] v;
  assign _07_ = ~(_18_ & _19_);
  assign _08_ = ~(_20_ & _21_);
  assign _09_ = ~(_22_ & _23_);
  assign _10_ = ~(_24_ & _25_);
  assign _11_ = ~(_26_ & _27_);
  assign _12_ = ~(_28_ & _29_);
  assign _13_ = ~(_30_ & _31_);
  assign _14_ = ~(_32_ & _33_);
  assign _15_ = ~(_34_ & _35_);
  assign _16_ = ~(_36_ & _37_);
  assign _17_ = ~(_38_ & _39_);
  assign _18_ = ~i[5];
  assign _19_ = ~i[4];
  assign _20_ = ~i[7];
  assign _21_ = ~i[6];
  assign _22_ = ~_01_;
  assign _23_ = ~_00_;
  assign _24_ = ~i[1];
  assign _25_ = ~i[0];
  assign _26_ = ~i[3];
  assign _27_ = ~i[2];
  assign _28_ = ~_03_;
  assign _29_ = ~_02_;
  assign _30_ = ~_04_;
  assign _31_ = ~addr_o[2];
  assign _32_ = ~i[3];
  assign _33_ = ~i[1];
  assign _34_ = ~i[7];
  assign _35_ = ~i[5];
  assign _36_ = ~_06_;
  assign _37_ = ~_05_;
  assign _38_ = ~_03_;
  assign _39_ = ~_01_;
  assign { addr[26:22], addr[19:18], addr[15:0] } = { addr_o, 5'hxx, i[7], 1'hx, i[5], 1'hx, i[3], 1'hx, i[1], 8'h00 };
  assign \rof[1].rof1[0].vs  = i[1:0];
  assign \rof[1].rof1[1].vs  = i[3:2];
  assign \rof[1].rof1[2].vs  = i[5:4];
  assign \rof[1].rof1[3].vs  = i[7:6];
  assign \rof[2].rof1[0].vs  = { addr[17], 1'hx };
  assign \rof[2].rof1[1].vs  = { addr[21], 1'hx };
  assign \rof[3].rof1[0].vs  = { addr_o[2], 1'hx };
  assign v = { v_o, 3'hx, addr_o[2], 5'hxx, addr[21], 3'hx, addr[17], 2'hx, i };
  assign _00_ = _07_;
  assign _01_ = _08_;
  assign addr_o[2] = _09_;
  assign _02_ = _10_;
  assign _03_ = _11_;
  assign _04_ = _12_;
  assign v_o = 1;
  assign _05_ = _14_;
  assign _06_ = _15_;
  assign addr_o[0] = _16_;
  assign addr_o[1] = _17_;
endmodule
