/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "xor2" *)
(* top =  1  *)
(* src = "xor2.soln.sv:1.1-8.10" *)
module xor2(a_i, b_i, c_o);
  (* src = "xor2.soln.sv:2.16-2.19" *)
  input [0:0] a_i;
  wire [0:0] a_i;
  (* src = "xor2.soln.sv:3.16-3.19" *)
  input [0:0] b_i;
  wire [0:0] b_i;
  (* src = "xor2.soln.sv:4.17-4.20" *)
  output [0:0] c_o;
  wire [0:0] c_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  assign _0_ = _1_ & _2_;
  assign _1_ = ~b_i;
  assign _2_ = ~a_i;
  assign _3_ = ~_0_;
  assign c_o = _3_;
endmodule
